apiVersion: v1
baseDomain: ocp.php
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 1 
metadata:
  name: ocp-clus 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
pullSecret: '{"auths": ...}' 
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB2Z6p1njNULoIOJitgXOukJo0S4LA8p+uukxvbRsegh root@ocp-service' 
