apiVersion: v1
baseDomain: lab.ocp.php
compute: 
- hyperthreading: Enabled 
  name: worker
  replicas: 0 
controlPlane: 
  hyperthreading: Enabled 
  name: master
  replicas: 1 
metadata:
  name: ocp-clus 
networking:
  clusterNetwork:
  - cidr: 10.244.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 192.168.2.0/24
platform:
  none: {} 
pullSecret: '{""}' 
sshKey: '' 
proxy:
  httpProxy: http://192.168.2.210:3128
  httpsProxy: http://192.168.2.210:3128
  noProxy: ocp-service.lab.ocp.php,.ocp-clus.lab.ocp.php,api.ocp-clus.lab.ocp.php,api-int.ocp-clus.lab.ocp.php,192.168.2.0/24,.apps.ocp-clus.lab.ocp.php
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
 
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - ocp-service.lab.ocp.php:8443/openshift/ocp4
  source: quay.io/openshift/okd
- mirrors:
  - ocp-service.lab.ocp.php:8443/openshift/ocp4
  source: quay.io/openshift/okd-content
